backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Subject", name: "subject", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
  - name: "updates"
    label: "Updates"
    folder: "content/updates"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser", name: "teaser", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Date", name: "date_published", widget: "date" }
