backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{first_name}}-{{last_name}}"
    identifier_field: last_name
    fields:
      - { label: "First name", name: "first_name", widget: "string" }
      - { label: "Last name", name: "last_name", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Subject", name: "subject", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["he", "en"],
        }
  - name: "updates"
    label: "Updates"
    folder: "content/updates"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser", name: "teaser", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Date", name: "date_published", widget: "date" }

  - name: "sponsors"
    label: "Sponsors"
    folder: "content/sponsors"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", allow_multiple: false }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["sponsor", "exhibitor", "media"],
        }
  - name: "radar_trends"
    label: "Radar/trends"
    folder: "content/radar/trends"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          options:
            [
              "Frontend",
              "Backend",
              "Devops",
              "Mobile",
              "Techniques",
              "Platforms",
            ],
          multiple: true,
        }
  - name: "radar_contributors"
    label: "radar/contributors"
    folder: "content/radar/contributors"
    create: true
    slug: "{{first_name}}-{{last_name}}"
    identifier_field: last_name
    fields:
      - { label: "First name", name: "first_name", widget: "string" }
      - { label: "Last name", name: "last_name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
      }
  - name: "schedule"
    label: "Schedule"
    folder: "content/schedule"
    create: true
    slug: "{{time}}"
    identifier_field: "time"
    fields: 
      - {label: "Time", name: "time", widget: "string" }
      - label: "Speakers"
        name: "speakers"
        widget: "object"
        fields: 
        - {label: "Backend/ML", name: "backend", widget: "relation", collection: "speakers", valueField: "last_name", searchFields:["first_name", "last_name"], required: false} 
        - {label: "DevOps", name: "devops", widget: "relation", collection: "speakers", valueField: "last_name", searchFields:["first_name", "last_name"], required: false} 
        - {label: "Frontend", name: "frontend", widget: "relation", collection: "speakers", valueField: "last_name", searchFields:["first_name", "last_name"], required: false} 
        - {label: "Mobile&Things", name: "mobile", widget: "relation", collection: "speakers", valueField: "last_name", searchFields:["first_name", "last_name"], required: false}
      - {label: "Mark as break", name: "is_break", widget: "boolean", required: false}
      
     
